### ISSUE TITLE
你好，咨询你一件事情。

### ISSUE THREAD

**Issue by zhipingyang120** [ShawnFree/hello-world#2]
我看见你回答了李俊老师讨论群里的关于无法下载GIT的疑问，你的
The solution is:

add 
192.30.253.112  github.com
192.30.253.113  github.com
to your hosts file
scoop install aria2
3. install git
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
scoop install git
 

repeat step 3 until the installation is successful,make sure your network is stable
 
another solution :

download right PortableGit-2.23.0-32-bit.7z.exe for your computer
put it in your scoop/cache folder
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.

scoop install git

我先是采用了第一种方法：通过网上搜索如何将网址添加入hosts文件，然后scoop install aria2
出现了这个问题：
PS C:\Users\Administrator> scoop install aria2
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of aria2 failed.
Run 'scoop uninstall aria2' before retrying the install.
WARN  'aria2' () is already installed.
Use 'scoop update aria2' to install a new version.
PS C:\Users\Administrator> scoop uninstall aria2
Uninstalling 'aria2' ().
'aria2' was uninstalled.
PS C:\Users\Administrator> scoop install aria2
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'aria2' (1.35.0-1) [64bit]
aria2-1.35.0-win-64bit-build1.zip (2.1 MB) [>                         ]   0%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
URL https://github.com/aria2/aria2/releases/download/release-1.35.0/aria2-1.35.0-win-64bit-build1.zip is not valid
PS C:\Users\Administrator> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\Administrator> scoop  uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\Administrator> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [>                         ]   0%
还是无法下载。

于是，我采用了第二种解决办法，通过迅雷下载了PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) 这个文件，并将文件移动到scoop/cache文件夹里，
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.

scoop install git

仍旧无法安装，我该怎么办啊？
请多指教

**Comment by wangbingfeng** [comment]
第一种方法，要多试几次(每次要等到命令自己终止，不要自己手动关闭)，要有足够的耐心；
第二种方法，要注意的你的文件（下载的文件地址必须为命令行界面提示的地址）是必须是正确的，否则会出现安装失败，你要下载的文件；
我的情况是出现checksum不正确，默认会找cache中的文件，第二种方法你给的提示不足够详细，最好是错误截图。

错误中链接，自己可以复制出来在浏览器打开，看能否访问，如果出现不能访问，多试几次，因为有可能网络不稳定

下面地址是我自己安装过程问题记录，供你参考
[https://blog.csdn.net/wangbingfengf98/article/details/102759498](url)

**Comment by zhipingyang120** [comment]
好的，我再来试一试，感谢！！



---原始邮件---
发件人: "wangbingfeng"<notifications@github.com&gt;
发送时间: 2019年11月2日(星期六) 晚上7:28
收件人: "wangbingfeng/hello-world"<hello-world@noreply.github.com&gt;;
抄送: "zhipingyang120"<905227121@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangbingfeng/hello-world] 你好，咨询你一件事情。 (#2)



第一种方法，要多试几次，要有足够的耐心；
 第二种方法，要注意的你的文件是必须是正确的，否则会出现安装失败，你要下载的文件；
 我的情况是出现checksum不正确，默认会找cache中的文件，第二种方法你给的提示不足够详细，最好是错误截图。
 
错误中链接，自己可以复制出来在浏览器打开，看能否访问，如果出现不能访问，多试几次，因为有可能网络不稳定
